apiVersion: v1
kind: Service
metadata:
  name: practica-final-service
spec:
  type: LoadBalancer
  selector:
    app: practica-final
  ports:
    - protocol: TCP
      name: cliente
      port: 4100
      targetPort: 4100
    - protocol: TCP
      name: servidor
      port: 3000
      targetPort: 3000
